In [5]:
import pandas as pd
import numpy as np
df = pd.read_csv('CovidIndiaData-01-04-2020.csv')
pd.read_csv('CovidIndiaData-01-04-2020.csv')

,Confirmed,CountryReg,Deaths,LastUpdate,Latitude,Longitude,Province,Recovered,week,Recovery_Percentage,Death_Percentage,Percent_of_change_over_last_day,No_Of_Days
0,1,India,0,2020-01-30,0.000000,0.00000,0,0,5,0.0,0.0,0.0,0
1,1,India,0,2020-01-31,0.000000,0.00000,0,0,5,0.0,0.0,0.0,1
2,1,India,0,2020-01-31,0.000000,0.00000,0,0,5,0.0,0.0,0.0,2
3,2,India,0,2020-02-02,0.000000,0.00000,0,0,5,0.0,0.0,100.0,3
4,3,India,0,2020-02-03,0.000000,0.00000,0,0,6,0.0,0.0,50.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,887,India,20,2020-03-27,20.593684,78.96288,0,73,13,8.0,2.0,22.0,57
58,987,India,24,2020-03-28,20.593684,78.96288,0,84,13,9.0,2.0,11.0,58
59,1024,India,27,2020-03-29,20.593684,78.96288,0,95,13,9.0,3.0,4.0,59
60,1251,India,32,2020-03-30,20.593684,78.96288,0,102,14,8.0,3.0,22.0,60
61,1397,India,35,2020-03-31,20.593684,78.96288,0,123,14,9.0,3.0,12.0,61

In [6]:
df.head(10)

,Confirmed,CountryReg,Deaths,LastUpdate,Latitude,Longitude,Province,Recovered,week,Recovery_Percentage,Death_Percentage,Percent_of_change_over_last_day,No_Of_Days
0,1,India,0,2020-01-30,0.0,0.0,0,0,5,0.0,0.0,0.0,0
1,1,India,0,2020-01-31,0.0,0.0,0,0,5,0.0,0.0,0.0,1
2,1,India,0,2020-01-31,0.0,0.0,0,0,5,0.0,0.0,0.0,2
3,2,India,0,2020-02-02,0.0,0.0,0,0,5,0.0,0.0,100.0,3
4,3,India,0,2020-02-03,0.0,0.0,0,0,6,0.0,0.0,50.0,4
5,3,India,0,2020-02-03,0.0,0.0,0,0,6,0.0,0.0,0.0,5
6,3,India,0,2020-02-03,0.0,0.0,0,0,6,0.0,0.0,0.0,6
7,3,India,0,2020-02-03,0.0,0.0,0,0,6,0.0,0.0,0.0,7
8,3,India,0,2020-02-03,0.0,0.0,0,0,6,0.0,0.0,0.0,8
9,3,India,0,2020-02-03,0.0,0.0,0,0,6,0.0,0.0,0.0,9

In [7]:
df.tail(10)

,Confirmed,CountryReg,Deaths,LastUpdate,Latitude,Longitude,Province,Recovered,week,Recovery_Percentage,Death_Percentage,Percent_of_change_over_last_day,No_Of_Days
52,396,India,7,2020-03-22,20.593700,78.96290,0,27,12,7.0,2.0,20.0,52
53,499,India,10,2020-03-23,20.593684,78.96288,0,34,13,7.0,2.0,26.0,53
54,536,India,10,2020-03-24,20.593684,78.96288,0,40,13,7.0,2.0,7.0,54
55,657,India,12,2020-03-25,20.593684,78.96288,0,43,13,7.0,2.0,23.0,55
56,727,India,20,2020-03-26,20.593684,78.96288,0,45,13,6.0,3.0,11.0,56
57,887,India,20,2020-03-27,20.593684,78.96288,0,73,13,8.0,2.0,22.0,57
58,987,India,24,2020-03-28,20.593684,78.96288,0,84,13,9.0,2.0,11.0,58
59,1024,India,27,2020-03-29,20.593684,78.96288,0,95,13,9.0,3.0,4.0,59
60,1251,India,32,2020-03-30,20.593684,78.96288,0,102,14,8.0,3.0,22.0,60
61,1397,India,35,2020-03-31,20.593684,78.96288,0,123,14,9.0,3.0,12.0,61

In [8]:
df.loc[10 : 20]

,Confirmed,CountryReg,Deaths,LastUpdate,Latitude,Longitude,Province,Recovered,week,Recovery_Percentage,Death_Percentage,Percent_of_change_over_last_day,No_Of_Days
10,3,India,0,2020-02-03,0.0,0.0,0,0,6,0.0,0.0,0.0,10
11,3,India,0,2020-02-03,0.0,0.0,0,0,6,0.0,0.0,0.0,11
12,3,India,0,2020-02-03,0.0,0.0,0,0,6,0.0,0.0,0.0,12
13,3,India,0,2020-02-03,0.0,0.0,0,0,6,0.0,0.0,0.0,13
14,3,India,0,2020-02-13,0.0,0.0,0,0,7,0.0,0.0,0.0,14
15,3,India,0,2020-02-13,0.0,0.0,0,0,7,0.0,0.0,0.0,15
16,3,India,0,2020-02-13,0.0,0.0,0,0,7,0.0,0.0,0.0,16
17,3,India,0,2020-02-16,0.0,0.0,0,3,7,100.0,0.0,0.0,17
18,3,India,0,2020-02-16,21.0,78.0,0,3,7,100.0,0.0,0.0,18
19,3,India,0,2020-02-16,0.0,0.0,0,3,7,100.0,0.0,0.0,19
20,3,India,0,2020-02-16,0.0,0.0,0,3,7,100.0,0.0,0.0,20

In [9]:
df.replace(to_replace={"Recovered":{0:"NA"}})

,Confirmed,CountryReg,Deaths,LastUpdate,Latitude,Longitude,Province,Recovered,week,Recovery_Percentage,Death_Percentage,Percent_of_change_over_last_day,No_Of_Days
0,1,India,0,2020-01-30,0.000000,0.00000,0,NA,5,0.0,0.0,0.0,0
1,1,India,0,2020-01-31,0.000000,0.00000,0,NA,5,0.0,0.0,0.0,1
2,1,India,0,2020-01-31,0.000000,0.00000,0,NA,5,0.0,0.0,0.0,2
3,2,India,0,2020-02-02,0.000000,0.00000,0,NA,5,0.0,0.0,100.0,3
4,3,India,0,2020-02-03,0.000000,0.00000,0,NA,6,0.0,0.0,50.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,887,India,20,2020-03-27,20.593684,78.96288,0,73,13,8.0,2.0,22.0,57
58,987,India,24,2020-03-28,20.593684,78.96288,0,84,13,9.0,2.0,11.0,58
59,1024,India,27,2020-03-29,20.593684,78.96288,0,95,13,9.0,3.0,4.0,59
60,1251,India,32,2020-03-30,20.593684,78.96288,0,102,14,8.0,3.0,22.0,60
61,1397,India,35,2020-03-31,20.593684,78.96288,0,123,14,9.0,3.0,12.0,61